spring.application.name=log-processing-service

server.port=8082


# ===============================
# PostgreSQL
# ===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/processing_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# ===============================
# JPA / Hibernate
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false


# ===============================
# Kafka
# ===============================

spring.kafka.bootstrap-servers=localhost:9092


# ===============================
# Kafka Consumer
# ===============================

spring.kafka.consumer.group-id=log-processing-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.enable-auto-commit=false

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JacksonJsonDeserializer

spring.kafka.consumer.properties.spring.json.value.default.type=com.hiba.logprocessingservice.event.LogCreatedEvent

spring.kafka.consumer.properties.spring.json.trusted.packages=com.hiba.logprocessingservice.event
spring.kafka.consumer.properties.spring.json.use.type.headers=false


# ===============================
# Kafka Producer
# ===============================

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JacksonJsonSerializer